version: '3.4'
services:
  redis:  
    image: redis:7
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    ports:
      - "6379"
