version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.4.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '3307:3306'
    volumes:
      - lpdb8:/var/lib/mysql
volumes:
  lpdb8:
    driver: local
