version: '3.8'
services:
  db:
    platform: linux/adm64
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '3306:3306'
    volumes:
      - dbx:/var/lib/mysql
volumes:
  dbx:
    driver: local
