# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345678 
    ports:
      - "5432:5432"
volumes:
  postgres:
    external: true
